### ISSUE TITLE
Why Emotion instead of JSS?

### ISSUE THREAD

**Issue by dwhitney** [lumihq/purescript-react-basic-emotion#1]
I'm curious why you've chosen to create this library when you've already got the JSS stuff in lumi-components? (not criticism, just curiosity)

**Comment by maddie927** [comment]
JSS was a very small change from where we were before (CSS files). It didn't really change how anything was done, only where the styles lived and whether you needed special webpack config to use them. Style loading also had to be done in the correct order to avoid some issues with cascading styles.

Emotion ties styles more closely to the components themselves, hopefully simplifying how selectors work and how tied styles are to magic strings (class names or custom element names). And it manages when and in what order styles are injected. Emotion also provides a mechanism at component render time for a parent to insert styles, even styles like `:hover` or media queries. It's just a little more powerful and flexible.

**Comment by maddie927** [comment]
Styled Components was also considered. It's very similar to Emotion, but lacks the "`React.createElement` alternative with a `css` prop" api which seemed like the easiest PS integration point.

**Comment by maddie927** [comment]
Closing, but feel free to ask if you have more questions
