### ISSUE TITLE
Auto prepend `var` with `--`

### ISSUE THREAD

**Issue by jvliwanag** [lumihq/purescript-react-basic-emotion#22]
Currently, to emit `var(--foo)`, it should be called as `E.var "--foo"`. However, since all css variables require the `--` prefix anyway, perhaps the call should be `E.var "foo"`.

This is a breaking change though.

**Comment by maddie927** [comment]
It probably should have been that way but this seems like it'd cause problems for existing uses of `var` so I'm not sure it's worth it. Open to other opinions though.

**Comment by jvliwanag** [comment]
It would be a very bad breaking change yeah. Since I'm using emotion for the first time though, I'm a bit biased and my opinion falls on releasing a major version update and noting the breaking change. Best to correct the api issue than have it linger.

**Comment by maddie927** [comment]
I'm not really convinced it's that bad the way it is now. It might be less convenient to type the extra `--`, but it isn't necessarily wrong one way or the other. I kind of like having it exactly mirror the variable name as you'd type it in CSS.

**Comment by jvliwanag** [comment]
Got it. Also, I agree it’s too much of a breaking change.
